schema = 1
record_type = "work"
id = "work.holy-see.universae-ecclesiae"
title = "Instruction Universae Ecclesiae on the application of Summorum Pontificum (30 April 2011)"
responsible = "Congregation for the Doctrine of the Faith; Pontifical Commission Ecclesia Dei"
work_type = "dicasterial-instruction"
languages = ["la"]
locus_pattern = 'complete-text'
description = "The instruction of 30 April 2011 by which the Pontifical Commission Ecclesia Dei, with the approval of Benedict XVI, gave norms for the application of the motu proprio Summorum Pontificum of 7 July 2007. Printed in Acta Apostolicae Sedis 103 (2011) 413-420."
relations = ["work.benedict-xvi.summorum-pontificum"]
