schema = 1
record_type = "work"
id = "work.benedict-xvi.summorum-pontificum"
title = "Summorum Pontificum"
responsible = "Pope Benedict XVI"
work_type = "apostolic-letter-motu-proprio"
alternate_titles = ["Apostolic Letter given Motu Proprio on the use of the Roman liturgy prior to the reform of 1970"]
languages = ["la"]
locus_pattern = 'complete-text'
description = "Benedict XVI's apostolic letter given motu proprio on 7 July 2007, effective 14 September 2007, designating the Missal of Paul VI the ordinary expression and the 1962 Missal an extraordinary expression of the lex orandi of the Roman Rite and regulating the latter's use."
relations = ["work.catholic-church.missale-romanum"]
