schema = 1
record_type = "work"
id = "work.john-paul-ii.ad-tuendam-fidem"
title = "Ad tuendam fidem"
responsible = "John Paul II"
work_type = "apostolic-letter-motu-proprio"
alternate_titles = ["Apostolic Letter Motu Proprio Ad tuendam fidem"]
languages = ["la", "en"]
locus_pattern = '(?:[1-7])'
description = "The apostolic letter issued motu proprio on 18 May 1998 inserting norms concerning definitive teaching into the Latin and Eastern codes."
